[package]
name = "quoted-string-parser"
version = "0.1.0"
edition = "2021"
authors = ["Santiago Carot-Nemesio <sancane@gmail.com"]
description = """
Quoted string parser for grammar defined in RFC3261
"""
documentation = "https://docs.rs/quoted-string-parser"
homepage = "https://github.com/sancane/quoted-string-parser"
repository = "https://github.com/sancane/quoted-string-parser"
readme = "README.md"
keywords = ["quoted-string", "parser", "rfc3261"]
license = "MIT/Apache-2.0"
categories = ["text-processing"]

[dependencies]
pest = "2.0"
pest_derive = "2.0"
